steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/binauthz-test/my-image', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/binauthz-test/my-image:latest']

  # 3. Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=binauthz-test'
    args:
      - '-c'
      - |
        kubectl create deployment my-new-deployment \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/binauthz-test/my-image:latest \
          --replicas=1

options:
  requestedVerifyOption: VERIFIED
  logging: CLOUD_LOGGING_ONLY
