steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/binauthz-test/my-image', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/binauthz-test/my-image:latest']

  # 3. Deploy to GKE
  #- name: 'gcr.io/cloud-builders/gke-deploy'
  #  args:
  #  - run
  #  - --image=us-central1-docker.pkg.dev/$PROJECT_ID/binauthz-test/my-image:latest
  #  - --location=us-central1
  #  - --cluster=autopilot-cluster-1

  # 3. Get the image digest
  #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #  entrypoint: 'bash'
  #  args:
  #    - '-c'
  #    - |
  #      IMAGE_DIGEST=$$(gcloud container images describe us-central1-docker.pkg.dev/$PROJECT_ID/binauthz-test/my-image:latest --format='value(digest)') &&
  #      echo "Image digest: $$IMAGE_DIGEST" &&
  #      echo "sha256:$$IMAGE_DIGEST" >> /workspace/digest
  #  id: get-image-digest
  #  volumes:
  #  - name: 'workspace'
  #    path: '/workspace'

  # 4. Deploy to GKE
  #- name: 'gcr.io/cloud-builders/kubectl'
  #  env:
  #    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  #    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
  #  args: ['create', 'deployment', 'my-new-deployment', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/binauthz-test/my-image:$$(cat /workspace/digest)']
  #  volumes:
  #  - name: 'workspace'
  #    path: '/workspace'

options:
  requestedVerifyOption: VERIFIED
  logging: CLOUD_LOGGING_ONLY
